# Definition of supported/accepted key algorithms
# This is used as option list for key generation
# as well as validation list for uploaded keys
# If you prefix a value with an underscore, is is accepted for validation
# but not presented on key generation
# The frontend will prefix all values with I18N_OPENXPKI_UI_KEY_XX_YY
# where XX is the key and yy is the value, so if you add new items make sure
# you also add a translation for it.
key:
    # Supported key algorithms (details need to be defined below!)
    alg:
      - rsa
      - ec
      #- dsa

    # Supported encryption algorithms (as taken by openssl)
    enc:
      - aes256

    # one of escrow, server, client, both
    # escrow is not implemented in workflows, yet!
    generate: both

    # Definition of key algorithms
    rsa:
        key_length:
          - 3072
          - 2048
          - 4096
          - 2048:4096

    ec:
        # those names are used for validation and to render the
        # option lit when server key generation is allowed
        # The preset is the recommended list from RFC5480
        # The possbile "named" curves are limited by the ones supported
        # by Crypt::PKCS10 at the moment. For NIST P-192/256 you can use
        # either the secpXXXr1 or primeXXXv1 alias
        curve_name:
          - prime256v1
          - secp384r1
          - secp521r1

        # Curves imply key lengths, setting key length here makes only
        # sense if you do NOT set curve names and want to allow all
        # ecc curves that provided a key length. Note this is the REAL
        # number of key bits, not the nominal security bits value!
        # Always set this with an underscore to hide the key lenght from the
        # key generation parameters dialog (it does not make sense there)
        # key_length:
        #  - _192
        #  - _256

    dsa:
        key_length:
          - 2048
          - 4096

validity:
    notafter: +01

digest: sha256
increasing_serials: 1
randomized_serial_bytes: 8

publish:
  - disk

# Profile extensions - set 0/1 as needed
extensions:
    basic_constraints:
        critical: 1
        ca: 0
        # only relevant with ca = 1
        path_length: 0

    subject_key_identifier:
        critical: 0
        hash: 1

    authority_key_identifier:
        critical: 0
        keyid:  1
        issuer: 0

    issuer_alt_name:
        critical: 0
        # If the issuer has no subject alternative name, copying returns
        # an empty extension, which is problematic with both RSA SecurId
        # tokens and Cisco devices!
        copy: 0

    crl_distribution_points:
        critical: 0
        uri:
            - http://pki.example.com/download/[% ISSUER.CN.0.replace(' ','_') %].crl

    authority_info_access:
        critical: 0
        ca_issuers: http://pki.example.com/download/[% ISSUER.CN.0.replace(' ','_') %].cer
        ocsp: http://ocsp.example.com/

    policy_identifier:
        critical: 0
        # you can combine both notations but do not use the same OID twice
        # short notation, if you just need OIDs
        # this is the globally defined "any policy"
        # oid: 2.5.29.32.0
        # for OIDs with CPS/Notice, put the OID as key.
        1.2.3.4:
          # CPS/Notice can be scalar or list
          cps:
            - http://pki.example.com/cps.html
            - http://pki.example.com/cps.html
          user_notice: This is a comment for policy oid 1.2.3.4

# I18N Placeholders for key settings
# I18N_OPENXPKI_UI_KEY_ALG
# I18N_OPENXPKI_UI_KEY_ALG_RSA
# I18N_OPENXPKI_UI_KEY_ALG_EC
# I18N_OPENXPKI_UI_KEY_ALG_DSA
# I18N_OPENXPKI_UI_KEY_ENC
# I18N_OPENXPKI_UI_KEY_ENC_AES256
# I18N_OPENXPKI_UI_KEY_ENC_3DES
# I18N_OPENXPKI_UI_KEY_ENC_IDEA
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH_2048
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH_3072
# I18N_OPENXPKI_UI_KEY_KEY_LENGTH_4096
# I18N_OPENXPKI_UI_KEY_CURVE_NAME
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_PRIME192V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_C2TNB191V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_PRIME239V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_SECT571R1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_PRIME256V1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_SECP384R1
# I18N_OPENXPKI_UI_KEY_CURVE_NAME_SECP521R1

